[package]
name = "varnavinyas-shabda"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Word origin classification and morphological decomposition"

[features]
iterative-decompose = []

[dependencies]
varnavinyas-akshar = { workspace = true }
varnavinyas-kosha = { workspace = true }
varnavinyas-types = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
toml = { workspace = true }
