use std::{env, fs, path::PathBuf};

use serde::Deserialize;
use varnavinyas_parikshak::{
    CheckOptions, Diagnostic, DiagnosticReason, check_text_with_options, diagnostic_reason_category,
};

#[cfg(not(feature = "grammar-pass"))]
const EXPECTED_SNAPSHOT: &str = include_str!("snapshots/corpus_diagnostics.snap");
#[cfg(feature = "grammar-pass")]
const EXPECTED_SNAPSHOT: &str = include_str!("snapshots/corpus_diagnostics_grammar_pass.snap");

#[cfg(not(feature = "grammar-pass"))]
const SNAPSHOT_FILE_NAME: &str = "corpus_diagnostics.snap";
#[cfg(feature = "grammar-pass")]
const SNAPSHOT_FILE_NAME: &str = "corpus_diagnostics_grammar_pass.snap";

#[derive(Debug, Deserialize)]
struct GoldEntry {
    incorrect: String,
    correct: String,
}

#[derive(Debug, Deserialize)]
struct GoldData {
    #[serde(default)]
    shuddha_table: Vec<GoldEntry>,
    #[serde(default)]
    hrasva_dirgha: Vec<GoldEntry>,
    #[serde(default)]
    chandrabindu: Vec<GoldEntry>,
    #[serde(default)]
    sha_sha_sa: Vec<GoldEntry>,
    #[serde(default)]
    ri_kri: Vec<GoldEntry>,
    #[serde(default)]
    halanta: Vec<GoldEntry>,
    #[serde(default)]
    ya_e: Vec<GoldEntry>,
    #[serde(default)]
    ksha_chhya: Vec<GoldEntry>,
    #[serde(default)]
    paragraph_correction: Vec<GoldEntry>,
}

#[derive(Debug, Deserialize)]
struct GrammarGold {
    sentence: Vec<GrammarSentence>,
}

#[derive(Debug, Deserialize)]
struct GrammarSentence {
    text: String,
}

struct CorpusCase {
    name: &'static str,
    mode: &'static str,
    text: String,
    options: CheckOptions,
}

#[test]
fn checker_corpus_diagnostics_snapshot() {
    let actual = render_snapshot();

    if env::var_os("VARNAVINYAS_UPDATE_CORPUS_SNAPSHOT").is_some() {
        let path = snapshot_path();
        fs::write(&path, &actual).expect("write corpus diagnostics snapshot");
        return;
    }

    assert_eq!(
        EXPECTED_SNAPSHOT, actual,
        "checker corpus snapshot changed; review the diff and rerun with \
         VARNAVINYAS_UPDATE_CORPUS_SNAPSHOT=1 to accept intentional behavior changes"
    );
}

fn render_snapshot() -> String {
    let cases = corpus_cases();
    let mut out = String::new();
    out.push_str("# Generated by crates/parikshak/tests/corpus_snapshot.rs\n");
    out.push_str("# Update intentionally with VARNAVINYAS_UPDATE_CORPUS_SNAPSHOT=1.\n\n");

    for case in cases {
        let diagnostics = check_text_with_options(&case.text, case.options);
        out.push_str(&format!(
            "## case={} mode={} bytes={} diagnostics={}\n",
            case.name,
            case.mode,
            case.text.len(),
            diagnostics.len()
        ));

        for (idx, diag) in diagnostics.iter().enumerate() {
            out.push_str(&format_diagnostic(idx, diag));
        }

        out.push('\n');
    }

    out
}

fn corpus_cases() -> Vec<CorpusCase> {
    let gold: GoldData =
        toml::from_str(include_str!("../../../docs/tests/gold.toml")).expect("parse gold.toml");
    let grammar: GrammarGold =
        toml::from_str(include_str!("../../../docs/tests/grammar_sentences.toml"))
            .expect("parse grammar_sentences.toml");

    let default = CheckOptions::default();
    let grammar_mode = CheckOptions {
        grammar: true,
        ..Default::default()
    };

    vec![
        CorpusCase {
            name: "gold-incorrect",
            mode: "default",
            text: gold_incorrect_text(&gold),
            options: default,
        },
        CorpusCase {
            name: "gold-correct",
            mode: "default",
            text: gold_correct_text(&gold),
            options: default,
        },
        CorpusCase {
            name: "grammar-fixtures",
            mode: "grammar",
            text: grammar
                .sentence
                .iter()
                .map(|entry| entry.text.as_str())
                .collect::<Vec<_>>()
                .join("\n"),
            options: grammar_mode,
        },
        CorpusCase {
            name: "government-notice-excerpt",
            mode: "default",
            text: GOVERNMENT_NOTICE_EXCERPT.to_string(),
            options: default,
        },
        CorpusCase {
            name: "government-style-excerpt",
            mode: "grammar",
            text: GOVERNMENT_STYLE_EXCERPT.to_string(),
            options: grammar_mode,
        },
    ]
}

fn gold_incorrect_text(data: &GoldData) -> String {
    all_gold_entries(data)
        .into_iter()
        .map(|entry| entry.incorrect.as_str())
        .collect::<Vec<_>>()
        .join(" । ")
}

fn gold_correct_text(data: &GoldData) -> String {
    all_gold_entries(data)
        .into_iter()
        .flat_map(|entry| entry.correct.split('/'))
        .collect::<Vec<_>>()
        .join(" । ")
}

fn all_gold_entries(data: &GoldData) -> Vec<&GoldEntry> {
    data.shuddha_table
        .iter()
        .chain(&data.hrasva_dirgha)
        .chain(&data.chandrabindu)
        .chain(&data.sha_sha_sa)
        .chain(&data.ri_kri)
        .chain(&data.halanta)
        .chain(&data.ya_e)
        .chain(&data.ksha_chhya)
        .chain(&data.paragraph_correction)
        .collect()
}

fn format_diagnostic(idx: usize, diag: &Diagnostic) -> String {
    let alternates = diag
        .alternate_reasons
        .iter()
        .map(format_alternate_reason)
        .collect::<Vec<_>>()
        .join(" || ");

    format!(
        "{idx:03}\tspan={}-{}\tkind={}\tcategory={}\trule={:?}\tconfidence={:.2}\tincorrect={}\tcorrection={}\texplanation={}\talternates={}\n",
        diag.span.0,
        diag.span.1,
        diag.kind.as_code(),
        diag.category.as_code(),
        diag.rule,
        diag.confidence,
        escape_field(&diag.incorrect),
        escape_field(&diag.correction),
        escape_field(&diag.explanation),
        escape_field(&alternates)
    )
}

fn format_alternate_reason(reason: &DiagnosticReason) -> String {
    format!(
        "rule={:?};category={};correction={};explanation={}",
        reason.rule,
        diagnostic_reason_category(reason).as_code(),
        reason.correction.as_deref().unwrap_or(""),
        reason.explanation
    )
}

fn escape_field(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('\t', "\\t")
        .replace('\n', "\\n")
}

fn snapshot_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("snapshots")
        .join(SNAPSHOT_FILE_NAME)
}

const GOVERNMENT_NOTICE_EXCERPT: &str = "\
नेपाल सरकारका औपचारिक निकायहरूमा प्रयोग गरिने भाषा, संविधान, ऐनकानुन, अदालत र सार्वजनिक सूचनामा मानक नेपाली भाषाको प्रयोग अनिवार्य मानिन्छ। \
राष्ट्रपति, प्रधानमन्त्री वा जिम्मेवार निकायबाट प्रसारण हुने विज्ञप्ति सार्वजनिक हुनुभन्दा अगाडि विज्ञहरूबाट भाषा सम्पादन गर्ने व्यवस्था मिलाउनुपर्छ। \
नेपालसरकार र परराष्ट्रमन्त्रालयले प्रेसविज्ञप्ति जारी गरे; शिक्षा मन्त्रालयमा छलफल भयो.";

const GOVERNMENT_STYLE_EXCERPT: &str = "\
कार्यक्रमको सम्बन्धमा सूचनाको आधारमा उपस्थितिको बारेमा छलफल भयो। \
घरको लागि समाजको निम्ति विषयको सम्बन्धमा तथ्यको आधारमा रोगको बारेमा विवरण तयार गरियो। \
म सबैलाई हार्दिक स्वागत गर्न चाहन्छु र यहाँको सहयोगप्रति म कृतघ्न छु.";
