#[cfg(any(test, feature = "test-seam"))]
use std::cell::RefCell;
use std::sync::LazyLock;

use fst::{Set, Streamer};

#[cfg(any(test, feature = "test-seam"))]
use crate::builder::build_fst_set;

use crate::origin_tag::{OriginTag, parse_origin_tag, parse_source_language};

/// Pre-built FST bytes generated by build.rs from `data/words.txt`.
/// Embedding the compact FST (~1-3 MB) rather than the raw word list (~4.9 MB)
/// reduces the WASM data section by ~2-4 MB.
static WORDS_FST_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/words.fst"));

/// Static headword metadata (tab-separated: word \t pos_tags).
static HEADWORDS_DATA: &str = include_str!("../../../data/headwords.tsv");

/// Reviewed lexicon quality overrides (tab-separated with a header row).
static LEXICON_OVERRIDES_DATA: &str = include_str!("../../../data/lexicon_overrides.tsv");

/// Global singleton lexicon, built once on first access.
static KOSHA: LazyLock<Kosha> = LazyLock::new(Kosha::from_prebuilt);

#[cfg(any(test, feature = "test-seam"))]
thread_local! {
    static TEST_KOSHA_OVERRIDE: RefCell<Option<&'static Kosha>> = const { RefCell::new(None) };
}

/// A metadata entry for a headword.
#[derive(Debug, Clone)]
pub struct WordEntry {
    /// The headword.
    pub word: &'static str,
    /// Part-of-speech tags (e.g., "[सं.] ना.", "वि.").
    pub pos: &'static str,
}

/// Reviewed quality tier for a lexicon form.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LexiconTier {
    /// The word is safe to use as a normal accepted form.
    Canonical,
    /// The word is generated or inflected, not necessarily a dictionary headword.
    GeneratedInflection,
    /// The word is attested but should not be treated as prescriptive.
    AttestedNonstandard,
    /// The word remains valid, but should not be used as a generic correction target.
    NonCorrectionTarget,
}

impl LexiconTier {
    fn from_code(code: &str) -> Option<Self> {
        match code {
            "canonical" => Some(Self::Canonical),
            "generated_inflection" => Some(Self::GeneratedInflection),
            "attested_nonstandard" => Some(Self::AttestedNonstandard),
            "non_correction_target" => Some(Self::NonCorrectionTarget),
            _ => None,
        }
    }
}

/// A reviewed override for one lexicon form.
#[derive(Debug, Clone)]
pub struct LexiconOverride {
    pub word: &'static str,
    pub tier: LexiconTier,
    pub reason: &'static str,
    pub source: &'static str,
    pub review_status: &'static str,
}

/// FST-based Nepali lexicon.
///
/// Uses an `fst::Set` for fast `contains()` checks over ~109K word forms,
/// and a sorted `Vec<WordEntry>` for headword metadata lookups.
pub struct Kosha {
    /// FST set for O(1) word existence checks.
    fst: Set<Vec<u8>>,
    /// Sorted full-word forms for nearby suggestion heuristics.
    words: Vec<String>,
    /// Sorted headword entries for binary-search metadata lookup.
    headwords: Vec<WordEntry>,
    /// Sorted reviewed lexicon quality overrides.
    overrides: Vec<LexiconOverride>,
}

impl Kosha {
    /// Build from the pre-compiled FST and static headword data.
    ///
    /// The FST bytes were generated by `build.rs` from `data/words.txt` at
    /// compile time. Wrapping pre-built bytes is near-zero cost compared to
    /// building the FST at runtime.
    fn from_prebuilt() -> Self {
        let fst = Set::new(WORDS_FST_BYTES.to_vec()).expect("pre-built FST should be valid");

        // Reconstruct the sorted word list by streaming the FST.
        // This is O(N) and replaces the previous runtime FST-build step.
        let words = words_from_fst(&fst);

        let headwords = parse_headwords(HEADWORDS_DATA);
        let overrides = parse_lexicon_overrides(LEXICON_OVERRIDES_DATA);
        Kosha {
            fst,
            words,
            headwords,
            overrides,
        }
    }

    /// Build from raw text data (used by the test seam only).
    #[cfg(any(test, feature = "test-seam"))]
    fn from_static_data(words_data: &'static str, headwords_data: &'static str) -> Self {
        let words_list: Vec<&str> = words_data.lines().filter(|l| !l.is_empty()).collect();
        let fst_bytes = build_fst_set(&words_list);
        let fst = Set::new(fst_bytes).expect("FST should be valid");
        let words = words_from_fst(&fst);
        let headwords = parse_headwords(headwords_data);
        let overrides = parse_lexicon_overrides(LEXICON_OVERRIDES_DATA);
        Kosha {
            fst,
            words,
            headwords,
            overrides,
        }
    }

    /// Check if a word exists in the lexicon.
    pub fn contains(&self, word: &str) -> bool {
        self.fst.contains(word)
    }

    /// Find one near-match candidate by character-level edit distance.
    ///
    /// This searches a bounded lexicographic window around the insertion point,
    /// avoiding a full-lexicon scan while keeping Unicode-aware matching.
    pub fn suggest_nearby(&self, word: &str, max_distance: usize) -> Option<String> {
        if word.is_empty() {
            return None;
        }

        let idx = self
            .words
            .binary_search_by(|w| w.as_bytes().cmp(word.as_bytes()))
            .unwrap_or_else(|i| i);
        const WINDOW: usize = 256;
        let start = idx.saturating_sub(WINDOW);
        let end = (idx + WINDOW).min(self.words.len());

        let mut best_idx: Option<usize> = None;
        let mut best_dist = usize::MAX;
        for (i, candidate) in self.words[start..end].iter().enumerate() {
            let clen = candidate.chars().count();
            let wlen = word.chars().count();
            if clen.abs_diff(wlen) > max_distance {
                continue;
            }

            if let Some(dist) = bounded_levenshtein_chars(word, candidate, max_distance) {
                let is_better = dist < best_dist
                    || (dist == best_dist
                        && best_idx
                            .map(|bi| candidate.as_str() < self.words[start + bi].as_str())
                            .unwrap_or(true));
                if is_better {
                    best_idx = Some(i);
                    best_dist = dist;
                }
            }
        }

        best_idx.map(|i| self.words[start + i].clone())
    }

    /// Look up headword metadata (POS tags).
    /// Returns `None` if the word is not a known headword.
    pub fn lookup(&self, word: &str) -> Option<&WordEntry> {
        self.headwords
            .binary_search_by(|entry| entry.word.as_bytes().cmp(word.as_bytes()))
            .ok()
            .map(|idx| &self.headwords[idx])
    }

    /// Look up a reviewed lexicon quality override.
    pub fn override_for(&self, word: &str) -> Option<&LexiconOverride> {
        self.overrides
            .binary_search_by(|entry| entry.word.as_bytes().cmp(word.as_bytes()))
            .ok()
            .map(|idx| &self.overrides[idx])
    }

    /// Return the reviewed tier for a form, or canonical for normal lexicon hits.
    pub fn lexicon_tier(&self, word: &str) -> Option<LexiconTier> {
        if let Some(entry) = self.override_for(word) {
            return Some(entry.tier);
        }
        (self.contains(word) || self.lookup(word).is_some()).then_some(LexiconTier::Canonical)
    }

    /// Whether a form is safe to use as a generic correction target.
    ///
    /// This is stricter than `contains()`: a word can be valid and attested but
    /// still unsafe as a rule-generated correction target.
    pub fn is_correction_target(&self, word: &str) -> bool {
        match self.lexicon_tier(word) {
            Some(LexiconTier::Canonical | LexiconTier::GeneratedInflection) => true,
            Some(LexiconTier::AttestedNonstandard | LexiconTier::NonCorrectionTarget) => false,
            None => false,
        }
    }

    /// Number of word forms in the FST.
    pub fn word_count(&self) -> usize {
        self.fst.len()
    }

    /// Number of headwords with metadata.
    pub fn headword_count(&self) -> usize {
        self.headwords.len()
    }

    /// Look up a word's origin from its dictionary metadata tags.
    ///
    /// Parses the `[सं.]`, `[फा.]`, `[अङ्.]` etc. tags from the headword's
    /// POS field using the Nepali Brihat Shabdakosha abbreviation legend.
    /// Returns `None` if the word is not a headword or has no origin tag.
    pub fn origin_of(&self, word: &str) -> Option<OriginTag> {
        let entry = self.lookup(word)?;
        parse_origin_tag(entry.pos)
    }

    /// Look up a word's source language from its dictionary metadata tags.
    ///
    /// Returns the human-readable language name (e.g., "फारसी", "अरबी", "संस्कृत").
    /// Returns `None` if the word is not a headword or has no recognized language tag.
    pub fn source_language_of(&self, word: &str) -> Option<&'static str> {
        let entry = self.lookup(word)?;
        parse_source_language(entry.pos)
    }
}

/// Reconstruct the sorted word list by streaming the FST.
fn words_from_fst(fst: &Set<Vec<u8>>) -> Vec<String> {
    let mut stream = fst.stream();
    let mut words = Vec::with_capacity(fst.len());
    while let Some(key) = stream.next() {
        if let Ok(s) = std::str::from_utf8(key) {
            words.push(s.to_string());
        }
    }
    words
}

/// Parse headword metadata from TSV text.
fn parse_headwords(headwords_data: &'static str) -> Vec<WordEntry> {
    let mut headwords: Vec<WordEntry> = headwords_data
        .lines()
        .filter_map(|line| {
            let mut parts = line.splitn(2, '\t');
            let word = parts.next()?.trim();
            if word.is_empty() {
                return None;
            }
            let pos = parts.next().unwrap_or("").trim();
            Some(WordEntry { word, pos })
        })
        .collect();
    headwords.sort_by(|a, b| a.word.as_bytes().cmp(b.word.as_bytes()));
    headwords
}

/// Parse reviewed lexicon quality overrides from TSV text.
fn parse_lexicon_overrides(overrides_data: &'static str) -> Vec<LexiconOverride> {
    let mut lines = overrides_data.lines();
    let header = lines
        .next()
        .expect("lexicon overrides must have a header row");
    assert_eq!(
        header, "word\ttier\treason\tsource\treview_status",
        "unexpected lexicon override header"
    );

    let mut overrides = Vec::new();
    for (line_idx, line) in lines.enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let fields: Vec<&'static str> = line.split('\t').collect();
        assert_eq!(
            fields.len(),
            5,
            "lexicon override line {} must have 5 TSV fields",
            line_idx + 2
        );

        let [word, tier_code, reason, source, review_status] =
            <[&'static str; 5]>::try_from(fields).expect("checked field count");
        assert!(
            !word.is_empty(),
            "lexicon override line {} has empty word",
            line_idx + 2
        );
        assert!(
            !reason.is_empty() && !source.is_empty() && !review_status.is_empty(),
            "lexicon override line {} must include provenance fields",
            line_idx + 2
        );
        let tier = LexiconTier::from_code(tier_code).unwrap_or_else(|| {
            panic!(
                "lexicon override line {} has unknown tier `{}`",
                line_idx + 2,
                tier_code
            )
        });
        overrides.push(LexiconOverride {
            word,
            tier,
            reason,
            source,
            review_status,
        });
    }

    overrides.sort_by(|a, b| a.word.as_bytes().cmp(b.word.as_bytes()));
    for pair in overrides.windows(2) {
        assert_ne!(
            pair[0].word, pair[1].word,
            "duplicate lexicon override for {}",
            pair[0].word
        );
    }
    overrides
}

#[cfg(any(test, feature = "test-seam"))]
struct TestKoshaResetGuard {
    previous: Option<&'static Kosha>,
}

#[cfg(any(test, feature = "test-seam"))]
impl Drop for TestKoshaResetGuard {
    fn drop(&mut self) {
        TEST_KOSHA_OVERRIDE.with(|slot| {
            slot.replace(self.previous);
        });
    }
}

/// Run a closure with a scoped test lexicon override.
///
/// This is available only for tests (or with `test-seam` feature) and resets
/// automatically when the closure exits.
///
/// Note: this helper intentionally leaks the constructed `Kosha` instance via
/// `Box::leak` to satisfy `'static` storage in the thread-local override.
/// This is acceptable for short-lived test execution, but should not be used in
/// long-running loops in production-like processes.
#[cfg(any(test, feature = "test-seam"))]
pub fn with_test_kosha<R>(
    words_data: &'static str,
    headwords_data: &'static str,
    f: impl FnOnce() -> R,
) -> R {
    let custom = Box::leak(Box::new(Kosha::from_static_data(
        words_data,
        headwords_data,
    )));
    let previous = TEST_KOSHA_OVERRIDE.with(|slot| slot.replace(Some(custom)));
    let _reset = TestKoshaResetGuard { previous };
    f()
}

/// Get a reference to the global lexicon singleton.
pub fn kosha() -> &'static Kosha {
    #[cfg(any(test, feature = "test-seam"))]
    {
        if let Some(override_kosha) = TEST_KOSHA_OVERRIDE.with(|slot| *slot.borrow()) {
            return override_kosha;
        }
    }

    &KOSHA
}

fn bounded_levenshtein_chars(a: &str, b: &str, max_distance: usize) -> Option<usize> {
    if a == b {
        return Some(0);
    }
    let a_chars: Vec<char> = a.chars().collect();
    let b_chars: Vec<char> = b.chars().collect();
    if a_chars.len().abs_diff(b_chars.len()) > max_distance {
        return None;
    }

    let mut prev: Vec<usize> = (0..=b_chars.len()).collect();
    let mut curr: Vec<usize> = vec![0; b_chars.len() + 1];

    for (i, &ac) in a_chars.iter().enumerate() {
        curr[0] = i + 1;
        let mut row_min = curr[0];
        for (j, &bc) in b_chars.iter().enumerate() {
            let cost = if ac == bc { 0 } else { 1 };
            curr[j + 1] = (prev[j + 1] + 1).min(curr[j] + 1).min(prev[j] + cost);
            row_min = row_min.min(curr[j + 1]);
        }
        if row_min > max_distance {
            return None;
        }
        std::mem::swap(&mut prev, &mut curr);
    }

    let dist = prev[b_chars.len()];
    (dist <= max_distance).then_some(dist)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_kosha_override_is_scoped() {
        const WORD: &str = "टेस्टशब्दनिश्चित";
        assert!(!kosha().contains(WORD));

        with_test_kosha(
            "टेस्टशब्दनिश्चित\n",
            "टेस्टशब्दनिश्चित\tना.\n",
            || {
                assert!(kosha().contains(WORD));
            },
        );

        assert!(!kosha().contains(WORD));
    }

    #[test]
    fn test_kosha_override_supports_nesting() {
        const WORD1: &str = "पहिलोनमूना";
        const WORD2: &str = "दोस्रोनमूना";

        with_test_kosha(
            "पहिलोनमूना\n",
            "पहिलोनमूना\tना.\n",
            || {
                assert!(kosha().contains(WORD1));
                assert!(!kosha().contains(WORD2));

                with_test_kosha(
                    "दोस्रोनमूना\n",
                    "दोस्रोनमूना\tना.\n",
                    || {
                        assert!(!kosha().contains(WORD1));
                        assert!(kosha().contains(WORD2));
                    },
                );

                assert!(kosha().contains(WORD1));
                assert!(!kosha().contains(WORD2));
            },
        );
    }

    #[test]
    fn test_suggest_nearby_returns_close_match() {
        with_test_kosha(
            "अध्ययन\nआकाश\n",
            "अध्ययन\tना.\nआकाश\tना.\n",
            || {
                let hit = kosha().suggest_nearby("अध्यन", 1);
                assert_eq!(hit.as_deref(), Some("अध्ययन"));
            },
        );
    }

    #[test]
    fn lexicon_override_keeps_word_valid_but_blocks_correction_target() {
        let k = kosha();
        assert!(k.contains("ओठे"));

        let override_entry = k.override_for("ओठे").expect("ओठे override");
        assert_eq!(override_entry.tier, LexiconTier::NonCorrectionTarget);
        assert!(!override_entry.reason.is_empty());
        assert!(!override_entry.source.is_empty());
        assert!(!override_entry.review_status.is_empty());

        assert_eq!(k.lexicon_tier("ओठे"), Some(LexiconTier::NonCorrectionTarget));
        assert!(!k.is_correction_target("ओठे"));
        assert!(k.is_correction_target("नेपाल"));
    }
}
